# Generated by Django 5.1.3 on 2024-11-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='fen_notations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
