# Generated by Django 5.1.4 on 2024-12-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_remove_annotation_body_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='context',
            field=models.CharField(default='http://www.w3.org/ns/anno.jsonld', max_length=255),
        ),
    ]
