blank_issues_enabled: false
contact_links:
  - name: Generic Issue Template
    url: https://github.com/bounswe/bounswe2024group12/issues/new?template=generic-issue-template.md
    about: A simple issue template for any kind of issue.